model:
  name: 'osnet_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['VeRi']
  targets: ['VeRi']
  height: 320
  width: 320          #veri
  combineall: False
  transforms: ['random_flip']
  save_dir: '../log/veri_im_osnet_x1_0_tri_320x320_adam_cosine'
#  save_dir: '../log/veri_im_osnet_x1_0_tri_320x320_adam_cosine_lr45'
loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.
    weight_x: 1.
    margin: 0. # 0.-->softmargin
sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4

train:
  optim: 'adam'
  lr: 0.000035
  #  lr: 0.0015
  max_epoch: 250
  batch_size: 64
  lr_scheduler: 'warmup'
  stepsize: [60, 90]

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: True

#** Results ** lr35 250 最高
#mAP: 77.5%
#CMC curve
#Rank-1  : 96.5%
#Rank-5  : 98.4%
#Rank-10 : 99.0%
#Rank-20 : 99.5%
#Checkpoint saved to "../log/veri_im_osnet_x1_0_tri_320x320_adam_cosine/model/model.pth.tar-250"
#

#** Results ** lr45 250 反而下降了
#mAP: 77.1%
#CMC curve
#Rank-1  : 96.2%
#Rank-5  : 98.5%
#Rank-10 : 99.0%
#Rank-20 : 99.3%
#Checkpoint saved to "../log/veri_im_osnet_x1_0_tri_320x320_adam_cosine_lr45/model/model.pth.tar-250"
